// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGpljTn-5mO2rFPM1mRdNFc2I_1M9JdVU',
    appId: '1:643994979441:web:533077cbb9a6444858dfd0',
    messagingSenderId: '643994979441',
    projectId: 'cinemixe-app-8926b',
    authDomain: 'cinemixe-app-8926b.firebaseapp.com',
    storageBucket: 'cinemixe-app-8926b.appspot.com',
    measurementId: 'G-H57E7JRY28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqPsvK84tOqVohGq9UbbDSnUQ51x-JDo',
    appId: '1:643994979441:android:86623394649c83e758dfd0',
    messagingSenderId: '643994979441',
    projectId: 'cinemixe-app-8926b',
    storageBucket: 'cinemixe-app-8926b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSRxYpUvorsYPU45kX3mtWSG08n2_4t10',
    appId: '1:643994979441:ios:fc7dc13ff447e24e58dfd0',
    messagingSenderId: '643994979441',
    projectId: 'cinemixe-app-8926b',
    storageBucket: 'cinemixe-app-8926b.appspot.com',
    iosClientId: '643994979441-gh6m1mha0jbc689282ior2v6ri71gdvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemixe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSRxYpUvorsYPU45kX3mtWSG08n2_4t10',
    appId: '1:643994979441:ios:88b0a383ac7b752b58dfd0',
    messagingSenderId: '643994979441',
    projectId: 'cinemixe-app-8926b',
    storageBucket: 'cinemixe-app-8926b.appspot.com',
    iosClientId: '643994979441-92u8kjpt9l60i9huk0k8v8pofu5suc5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemixe.RunnerTests',
  );
}
