// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtHu5I1pDPdS3PYAwPCrTLHlQ1ch6rN88',
    appId: '1:711311729966:web:07df89a521744e2af6c6bf',
    messagingSenderId: '711311729966',
    projectId: 'cinemixe-app',
    authDomain: 'cinemixe-app.firebaseapp.com',
    storageBucket: 'cinemixe-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSvLjugf9CjYTx04HCsl1GertUPFwXjhc',
    appId: '1:711311729966:android:3672debf63c58266f6c6bf',
    messagingSenderId: '711311729966',
    projectId: 'cinemixe-app',
    storageBucket: 'cinemixe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXVejrN4FGSkAOPeO0JJFyGEoSKbBKPus',
    appId: '1:711311729966:ios:b15e05805d347b98f6c6bf',
    messagingSenderId: '711311729966',
    projectId: 'cinemixe-app',
    storageBucket: 'cinemixe-app.appspot.com',
    iosBundleId: 'com.example.cinemixe',
  );
}
